version: "3.7"

services:
  web:
    build: .
    volumes:
      - .:/var/www/html/
    ports:
      - "3000:80"
    restart: unless-stopped
    working_dir: /var/www/html

  db:
    image: mysql
    environment:
      - MYSQL_DATABASE=gymapi
      - MYSQL_PASSWORD=gymapi
      - MYSQL_ROOT_PASSWORD=m3rc3nary011
